import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import { Button, Field, CellGroup, Icon } from "vant";
import "vant/lib/index.css";
const app = createApp(App);
app.use(Field);
app.use(CellGroup);
app.use(Icon);
app.use(Button);
app.mount("#app");
